[build]
  command = "echo 'No build process needed'"
  publish = "."
  functions = "./netlify/functions"

[functions]
  included_files = ["./emails/**"]

[[plugins]]
  package = "@netlify/plugin-emails"
  pinned_version = "1"

[[plugins]]
  package = "@netlify/plugin-lighthouse"