functionsDirectory = "D:\\STAR\\Brandliftco\\netlify\\functions"
functionsDirectoryOrigin = "config"
headers = []
redirects = []

[build]
publish = "D:\\STAR\\Brandliftco"
publishOrigin = "config"
commandOrigin = "config"
command = "echo 'No build needed'"
functions = "D:\\STAR\\Brandliftco\\netlify\\functions"

  [build.environment]

  [build.processing]

    [build.processing.css]

    [build.processing.html]

    [build.processing.images]

    [build.processing.js]

  [build.services]

[functions]

  [functions.emails]
  included_files = [
    "./emails/**"
  ]

  [functions."*"]

[[plugins]]
origin = "ui"
package = "@netlify/plugin-lighthouse"

  [plugins.inputs]

[[plugins]]
origin = "ui"
package = "netlify-plugin-visual-diff"

  [plugins.inputs]

[[plugins]]
origin = "ui"
package = "netlify-plugin-cypress"

  [plugins.inputs]

[[plugins]]
origin = "ui"
package = "@netlify/plugin-emails"
pinned_version = "1"

  [plugins.inputs]